Repository Uul2/Jo2_Server, pull requests merged in 2024-08, with the labels that each got.

#2 [CHORE] 리드미 수정
  README.md
Labels: setting

#3 [SET] Member 도메인 셋팅
  src/main/java/com/jo2/server/common/entity/BaseTime.java
  src/main/java/com/jo2/server/common/support/RepositoryAdapter.java
  src/main/java/com/jo2/server/member/adapter/MemberFinder.java
  src/main/java/com/jo2/server/member/adapter/MemberSaver.java
  src/main/java/com/jo2/server/member/controller/MemberController.java
  src/main/java/com/jo2/server/member/entity/Member.java
  src/main/java/com/jo2/server/member/entity/enums/Gender.java
  src/main/java/com/jo2/server/member/exception/MemberException.java
  src/main/java/com/jo2/server/member/message/ErrorCode.java
  src/main/java/com/jo2/server/member/message/SuccessMessage.java
  src/main/java/com/jo2/server/member/repository/MemberRepository.java
  src/main/java/com/jo2/server/member/service/MemberService.java
Labels: setting

#4 [SET] Member 도메인 셋팅
  src/main/java/com/jo2/server/member/entity/Member.java
Labels: setting

#5 [SET] Chatting 도메인 셋팅
  src/main/java/com/jo2/server/chatting/controller/ChattingController.java
  src/main/java/com/jo2/server/chatting/exception/ChattingException.java
  src/main/java/com/jo2/server/chatting/message/ErrorCode.java
  src/main/java/com/jo2/server/chatting/message/SuccessMessage.java
  src/main/java/com/jo2/server/chatting/service/ChattingService.java
Labels: setting

#6 [SET] Weather 도메인 세팅
  src/main/java/com/jo2/server/weather/adapter/WeatherFinder.java
  src/main/java/com/jo2/server/weather/adapter/WeatherSaver.java
  src/main/java/com/jo2/server/weather/controller/WeatherController.java
  src/main/java/com/jo2/server/weather/entity/Weather.java
  src/main/java/com/jo2/server/weather/exception/WeatherException.java
  src/main/java/com/jo2/server/weather/message/ErrorCode.java
  src/main/java/com/jo2/server/weather/message/SuccessMessage.java
  src/main/java/com/jo2/server/weather/repository/WeatherRepository.java
  src/main/java/com/jo2/server/weather/service/WeatherService.java
Labels: setting

#7 [SET] Auth 도메인 셋팅
  src/main/java/com/jo2/server/auth/controller/AuthController.java
  src/main/java/com/jo2/server/auth/exception/AuthException.java
  src/main/java/com/jo2/server/auth/message/ErrorCode.java
  src/main/java/com/jo2/server/auth/message/SuccessMessage.java
  src/main/java/com/jo2/server/auth/service/AuthService.java
Labels: setting

#9 Feat/#8 weather
  src/main/java/com/jo2/server/common/dto/BaseResponse.java
  src/main/java/com/jo2/server/common/dto/ErrorResponse.java
  src/main/java/com/jo2/server/common/dto/SuccessResponse.java
  src/main/java/com/jo2/server/common/support/UriGenerator.java
  src/main/java/com/jo2/server/weather/adapter/WeatherFinder.java
  src/main/java/com/jo2/server/weather/controller/WeatherController.java
  src/main/java/com/jo2/server/weather/dto/reponse/AllWeatherResponse.java
  src/main/java/com/jo2/server/weather/dto/reponse/RecentWeatherResponse.java
  src/main/java/com/jo2/server/weather/entity/ScoreVO.java
  src/main/java/com/jo2/server/weather/entity/Weather.java
  src/main/java/com/jo2/server/weather/entity/WeatherList.java
  src/main/java/com/jo2/server/weather/exception/WeatherException.java
  src/main/java/com/jo2/server/weather/message/ErrorCode.java
  src/main/java/com/jo2/server/weather/message/SuccessMessage.java
  src/main/java/com/jo2/server/weather/repository/WeatherRepository.java
  src/main/java/com/jo2/server/weather/service/WeatherService.java
Labels: feat

#13 [SET] Analysis 도메인 셋팅
  src/main/java/com/jo2/server/analysis/adapter/AnalysisFinder.java
  src/main/java/com/jo2/server/analysis/adapter/AnalysisSaver.java
  src/main/java/com/jo2/server/analysis/controller/AnalysisController.java
  src/main/java/com/jo2/server/analysis/entity/Analysis.java
  src/main/java/com/jo2/server/analysis/exception/AnalysisException.java
  src/main/java/com/jo2/server/analysis/message/ErrorCode.java
  src/main/java/com/jo2/server/analysis/message/SuccessMessage.java
  src/main/java/com/jo2/server/analysis/repository/AnalysisRepository.java
  src/main/java/com/jo2/server/analysis/service/AnalysisService.java
Labels: setting

#14 [FEAT] 소셜 로그인 구현
  build.gradle
  src/main/java/com/jo2/server/auth/config/OpenFeignConfig.java
  src/main/java/com/jo2/server/auth/controller/AuthController.java
  src/main/java/com/jo2/server/auth/dto/request/UserSignInRequest.java
  src/main/java/com/jo2/server/auth/dto/response/ReissueGetResponse.java
  src/main/java/com/jo2/server/auth/dto/response/SignInGetResponse.java
  src/main/java/com/jo2/server/auth/exception/AuthException.java
  src/main/java/com/jo2/server/auth/jwt/JwtTokenProvider.java
  src/main/java/com/jo2/server/auth/jwt/JwtValidationType.java
  src/main/java/com/jo2/server/auth/jwt/domain/Token.java
  src/main/java/com/jo2/server/auth/jwt/repository/TokenRepository.java
  src/main/java/com/jo2/server/auth/jwt/service/TokenService.java
  src/main/java/com/jo2/server/auth/message/ErrorCode.java
  src/main/java/com/jo2/server/auth/message/SuccessMessage.java
  src/main/java/com/jo2/server/auth/service/AuthService.java
  src/main/java/com/jo2/server/auth/social/SocialType.java
  src/main/java/com/jo2/server/auth/social/google/GoogleSocialStrategy.java
  src/main/java/com/jo2/server/auth/social/google/api/GoogleAccessTokenClient.java
  src/main/java/com/jo2/server/auth/social/google/api/GoogleUserClient.java
  src/main/java/com/jo2/server/auth/social/google/api/dto/GoogleAccessTokenResponse.java
  src/main/java/com/jo2/server/auth/social/google/api/dto/GoogleUserInfoResponse.java
  src/main/java/com/jo2/server/auth/social/kakao/KaKaoSocialStrategy.java
  src/main/java/com/jo2/server/auth/social/kakao/api/KakaoAccessTokenClient.java
  src/main/java/com/jo2/server/auth/social/kakao/api/KakaoUserClient.java
  src/main/java/com/jo2/server/auth/social/kakao/api/dto/KakaoAccessTokenResponse.java
  src/main/java/com/jo2/server/auth/social/kakao/api/dto/KakaoAccount.java
  src/main/java/com/jo2/server/auth/social/kakao/api/dto/KakaoUserProfile.java
  src/main/java/com/jo2/server/auth/social/kakao/api/dto/KakaoUserResponse.java
  src/main/java/com/jo2/server/auth/strategy/SignInStrategy.java
  src/main/java/com/jo2/server/auth/strategy/SignInStrategyManager.java
  src/main/java/com/jo2/server/auth/strategy/dto/UserInfoResponse.java
  src/main/java/com/jo2/server/common/config/QueryDslConfig.java
  src/main/java/com/jo2/server/common/handler/ErrorHandler.java
  src/main/java/com/jo2/server/member/adapter/MemberCreator.java
  src/main/java/com/jo2/server/member/adapter/MemberFinder.java
  src/main/java/com/jo2/server/member/adapter/MemberSaver.java
  src/main/java/com/jo2/server/member/entity/Member.java
  src/main/java/com/jo2/server/member/message/ErrorCode.java
  src/main/java/com/jo2/server/member/repository/MemberRepository.java
  src/main/java/com/jo2/server/member/repository/MemberRepositoryCustom.java
  src/main/java/com/jo2/server/member/repository/MemberRepositoryImpl.java
Labels: feat

#15 [FIX] application-dev 수정
  src/main/java/com/jo2/server/auth/jwt/service/TokenService.java
  src/main/java/com/jo2/server/auth/social/kakao/KaKaoSocialStrategy.java
  src/main/resources/application-dev.yml
Labels: fix

#17 [FEAT] redisson 추가
  build.gradle
  src/main/java/com/jo2/server/auth/config/RedisConfig.java
Labels: feat

#21 [FEAT] redis config 추가
  src/main/java/com/jo2/server/auth/config/RedisConfig.java
Labels: fix

#23 [CHORE] ddl auto 변경
  src/main/resources/application-dev.yml
Labels: feat

#25 [CHORE] 소셜 로그인 수정
  src/main/java/com/jo2/server/auth/config/OpenFeignConfig.java
  src/main/java/com/jo2/server/auth/service/AuthService.java
  src/main/java/com/jo2/server/auth/social/kakao/KaKaoSocialStrategy.java
  src/main/java/com/jo2/server/auth/social/kakao/api/dto/KakaoAccount.java
  src/main/java/com/jo2/server/auth/social/kakao/api/dto/Profile.java
  src/main/resources/application-dev.yml
Labels: feat

#27 [FEAT] CorsConfig 추가
  src/main/java/com/jo2/server/common/config/CorsConfig.java
Labels: feat

#34 [FEAT] 정적 컨텐츠 API 구현
  src/main/java/com/jo2/server/contents/controller/ContentsController.java
  src/main/java/com/jo2/server/contents/dto/reponse/MainSentenceGetResponse.java
  src/main/java/com/jo2/server/contents/dto/reponse/VideoCardsGetResponse.java
  src/main/java/com/jo2/server/contents/entity/MainSentence.java
  src/main/java/com/jo2/server/contents/entity/VideoLink.java
  src/main/java/com/jo2/server/contents/message/SuccessMessage.java
  src/main/java/com/jo2/server/contents/service/ContentsService.java
Labels: feat

#38 [FEAT] JWT 토큰 검증 로직 추가
  src/main/java/com/jo2/server/auth/jwt/JwtTokenProvider.java
  src/main/java/com/jo2/server/chatserver/controller/ChatserverController.java
  src/main/java/com/jo2/server/common/config/WebConfig.java
  src/main/java/com/jo2/server/common/resolver/member/MemberId.java
  src/main/java/com/jo2/server/common/resolver/member/MemberIdHeaderResolver.java
  src/main/java/com/jo2/server/contents/controller/ContentsController.java
  src/main/java/com/jo2/server/contents/entity/VideoLink.java
  src/main/java/com/jo2/server/weather/controller/WeatherController.java
Labels: feat

#39 [FIX] 전체 분석기능 수정
  src/main/java/com/jo2/server/analysis/adapter/AnalysisCreator.java
  src/main/java/com/jo2/server/analysis/adapter/AnalysisDeleter.java
  src/main/java/com/jo2/server/analysis/adapter/AnalysisFinder.java
  src/main/java/com/jo2/server/analysis/adapter/AnalysisSaver.java
  src/main/java/com/jo2/server/analysis/dto/AnalysisResponse.java
  src/main/java/com/jo2/server/analysis/entity/Analysis.java
  src/main/java/com/jo2/server/analysis/repository/AnalysisRepository.java
  src/main/java/com/jo2/server/chatserver/client/ChatserverClient.java
  src/main/java/com/jo2/server/chatserver/client/dto/ChatserverAnalysisRequest.java
  src/main/java/com/jo2/server/chatserver/controller/ChatserverController.java
  src/main/java/com/jo2/server/chatserver/dto/response/ChatserverAnalysisResponse.java
  src/main/java/com/jo2/server/chatserver/service/ChatserverService.java
  src/main/java/com/jo2/server/weather/adapter/WeatherFinder.java
  src/main/java/com/jo2/server/weather/message/ErrorCode.java
  src/main/java/com/jo2/server/weather/repository/WeatherRepository.java
Labels: fix

#43 [CHORE Camel Case 적용
  src/main/java/com/jo2/server/chatserver/dto/request/ChatServerStartRequest.java
Labels: fix

#44 [FEAT] Weather 저장 기능 추가 및 불러오기 기능 수정
  src/main/java/com/jo2/server/chatserver/client/ChatserverClient.java
  src/main/java/com/jo2/server/chatserver/client/dto/ChatServerAnalysisRequest.java
  src/main/java/com/jo2/server/chatserver/client/dto/ChatserverAnalysisRequest.java
  src/main/java/com/jo2/server/chatserver/service/ChatserverService.java
  src/main/java/com/jo2/server/common/config/JpaAuditingConfig.java
  src/main/java/com/jo2/server/member/adapter/MemberCreator.java
  src/main/java/com/jo2/server/member/adapter/MemberFinder.java
  src/main/java/com/jo2/server/member/entity/Member.java
  src/main/java/com/jo2/server/member/message/ErrorCode.java
  src/main/java/com/jo2/server/member/repository/MemberRepository.java
  src/main/java/com/jo2/server/member/repository/MemberRepositoryCustom.java
  src/main/java/com/jo2/server/member/repository/MemberRepositoryImpl.java
  src/main/java/com/jo2/server/weather/adapter/WeatherFinder.java
  src/main/java/com/jo2/server/weather/adapter/WeatherSaver.java
  src/main/java/com/jo2/server/weather/controller/WeatherController.java
  src/main/java/com/jo2/server/weather/dto/reponse/AllWeatherResponse.java
  src/main/java/com/jo2/server/weather/dto/reponse/WeatherCreateResponse.java
  src/main/java/com/jo2/server/weather/dto/request/WeatherCreateRequest.java
  src/main/java/com/jo2/server/weather/entity/Weather.java
  src/main/java/com/jo2/server/weather/entity/WeatherList.java
  src/main/java/com/jo2/server/weather/repository/WeatherRepository.java
  src/main/java/com/jo2/server/weather/service/WeatherService.java
  src/main/java/com/jo2/server/weather/vo/WeatherVO.java
  src/main/resources/application-dev.yml
Labels: feat

#47 [CHORE] 로그인 응답 수정
  src/main/java/com/jo2/server/auth/dto/response/SignInGetResponse.java
  src/main/java/com/jo2/server/auth/service/AuthService.java
Labels: fix

#48 [CHORE] 리이슈 수정
  src/main/java/com/jo2/server/auth/controller/AuthController.java
Labels: feat

#50 [FEAT] WeatherExceptionHandler 추가
  src/main/java/com/jo2/server/common/handler/ErrorHandler.java
Labels: feat

#54 [FIX] 배포 origin 허용
  src/main/java/com/jo2/server/common/config/WebConfig.java
Labels: fix

#57 [CHORE] CORS 추가
  src/main/java/com/jo2/server/common/config/WebConfig.java
Labels: feat

#60 [CHORE] 인증 메세지 수정
  src/main/java/com/jo2/server/auth/controller/AuthController.java
  src/main/java/com/jo2/server/auth/jwt/JwtTokenProvider.java
  src/main/java/com/jo2/server/auth/message/ErrorCode.java
  src/main/java/com/jo2/server/common/resolver/member/MemberIdHeaderResolver.java
Labels: feat

#69 [FIX] Analysis DTO 수정
  src/main/java/com/jo2/server/chatserver/client/dto/ChatServerAnalysisRequest.java
  src/main/java/com/jo2/server/chatserver/client/dto/WeatherAnalysisVO.java
  src/main/java/com/jo2/server/chatserver/service/ChatserverService.java
Labels: fix
